# Generated by Django 5.2 on 2025-05-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
